# Generated by Django 2.1.3 on 2018-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraperETL', '0003_auto_20181127_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
