# Generated by Django 2.1.3 on 2018-12-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebScraperETL', '0004_product_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebScraperETL.Product'),
        ),
    ]
